### ISSUE TITLE
outdated at 8.3.0

### ISSUE THREAD

**Issue by vmwinckler** [GoldpawsStuff/Bagnon_ItemInfo#8] opened 2020-06-23 12:51 UTC
outdated at 8.3.0

**Comment by goldpaw** [comment] 2020-06-23 13:22
Yeah but does it work? with the "load out of date addons" checkbox? Not a bug if it does. It is tagged for 8.2.5, and works for 8.2.5, and if it works for 8.3.0 with the box checked, it's not bugged.

**Comment by goldpaw** [comment] 2020-09-25 16:57
Closing as it works with 9.x and is fully updated.

**Closed by goldpaw** 2020-09-25 16:57 UTC
