### ISSUE TITLE
Missing Library

### ISSUE THREAD

**Issue by Odysseas68** [GoldpawsStuff/Bagnon_ItemInfo#30] opened 2023-10-22 15:38 UTC
In ver 2.1.63 the library `AceLocale-3.0` is missing throwing a lua error. I correct this by copying the lib from another addon.

**Comment by Starlynk1** [comment] 2023-10-22 17:52
Same Issue here... 
```
2x Bagnon_ItemInfo/Embeds.xml:6 Couldn't open Bagnon_ItemInfo/Libs/AceLocale-3.0-6/AceLocale-3.0.xml
```

**Comment by Odysseas68** [comment] 2023-10-22 19:04
Copy the lib from any addon you have (i copy it from the `details` addon) to the libs directory and the error is gone.

**Comment by Starlynk1** [comment] 2023-10-22 19:16
I've got Ace3 installed seperately, so its really not needed. The problem is that either the library is missing from the release or that line needs to be removed from the embeds.xml file if it's not needed.

**Comment by Starlynk1** [comment] 2023-10-23 13:48
I feel ya @Goldpaw, my mind has been failing for a VERY long time. Thanks for the update!

**Comment by Goldpaw** [comment] 2023-10-23 13:58
Yeah, I totally forgot to add the actual embed line to the packager's meta file. Should be fixed now. 👍🏻

**Closed by Goldpaw** 2023-10-23 13:58 UTC
